version: '3.8'
services:
  app:
    image: openai-demo-app
    build:
      context: ./
      target: dev  # can change to production.
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"